import pandas as pd

df = pd.read_csv('scooter.csv')

print()
print(df.columns)
print()
print(df.dtypes)
print()
print(df.head())  # First 5 rows
print()
print(df.tail())  # Last 5 rows
print()
print(df.shape)  # Returns (rows, columns)
print()
print()

print(df.info())
print()
print(df.describe())
print()
print(df['start_location_name'].describe())
print()
print(df['DURATION'].value_counts(dropna=False))
print()
print(df['DURATION'].value_counts(normalize=True, dropna=False))
print()
print(df['start_location_name'].value_counts())
print()
print(df['start_location_name'].value_counts(normalize=True))
print()
print(df['end_location_name'].value_counts(dropna=False))
print()
print(df.isnull().sum())
print()
print(df['trip_id'].value_counts(bins=10))
print()
print(df['trip_id'].value_counts(bins=10, normalize=True))
print()